[menu]
background = "#080311"
background-alpha = 0.92
text = "#DFFBFF"
border = "hyprland.active-border"
border-alpha = 1.0
scrim = "#020106"
scrim-alpha = 0.58
selected-background = "#00F5FF"
selected-background-alpha = 0.14
selected-text = "#FF82EA"
selected-border = "hyprland.active-border"
selected-border-alpha = 0.9
