#!/usr/bin/env bash

set -Eeuo pipefail

theme_name="neon-overdrive"
plugin_id="neon-overdrive.cava"
begin_marker="-- BEGIN NEON OVERDRIVE MANAGED BLOCK"
end_marker="-- END NEON OVERDRIVE MANAGED BLOCK"

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
state_home="${XDG_STATE_HOME:-$HOME/.local/state}"
theme_dir="$config_home/omarchy/themes/$theme_name"
plugin_dir="$config_home/omarchy/plugins/$plugin_id"
autostart_file="$config_home/hypr/autostart.lua"
wallpaper_bin="$HOME/.local/bin/neon-overdrive-wallpaper"
wallpaper_dir="$data_home/neon-overdrive"
state_dir="$state_home/neon-overdrive"
state_file="$state_dir/install-state.env"

die() {
  printf 'Neon Overdrive uninstaller: %s\n' "$*" >&2
  exit 1
}

warn() {
  printf 'Neon Overdrive uninstaller: warning: %s\n' "$*" >&2
}

((EUID != 0)) || die "run this as your desktop user, not root"
command -v omarchy >/dev/null 2>&1 || die "Omarchy is required"
command -v jq >/dev/null 2>&1 || die "jq is required by Omarchy"

PREVIOUS_THEME=""
BACKGROUND_WAS_ENABLED=""
THEME_WAS_COPIED="false"
if [[ -r $state_file ]]; then
  # This file is generated by install.sh, owned by the current user, and mode 0600.
  # shellcheck disable=SC1090
  source "$state_file"
else
  warn "install state is missing; prior theme/background choices will be left alone"
fi

install -d -m 700 -- "$state_dir" "$state_dir/backups"
backup_dir="$state_dir/backups/uninstall-$(date -u +%Y%m%dT%H%M%SZ)-$$"
install -d -m 700 -- "$backup_dir"

backup_path() {
  local label=$1
  local path=$2
  [[ -e $path || -L $path ]] || return 0
  install -d -m 700 -- "$backup_dir/$(dirname -- "$label")"
  cp -a -- "$path" "$backup_dir/$label"
}

stash_managed() {
  local label=$1
  local path=$2
  local marker=$3
  [[ -e $path || -L $path ]] || return 0
  [[ -f $marker ]] || {
    warn "leaving unmanaged path in place: $path"
    return 0
  }
  install -d -m 700 -- "$backup_dir/removed/$(dirname -- "$label")"
  mv -- "$path" "$backup_dir/removed/$label"
}

backup_path config/hypr/autostart.lua "$autostart_file"
backup_path config/omarchy/shell.json "$config_home/omarchy/shell.json"

if [[ -x $wallpaper_bin ]] && grep -Fq 'Managed by Neon Overdrive' "$wallpaper_bin"; then
  "$wallpaper_bin" stop || true
fi

plugin_json=$(omarchy plugin list --json)
if jq -e --arg id "$plugin_id" 'any(.[]; .id == $id and .enabled == true)' <<<"$plugin_json" >/dev/null; then
  omarchy plugin disable "$plugin_id"
fi

if [[ $BACKGROUND_WAS_ENABLED == true ]]; then
  omarchy plugin enable omarchy.background
fi

if [[ -e $plugin_dir && -f $plugin_dir/.neon-overdrive-managed ]]; then
  install -d -m 700 -- "$backup_dir/removed/config/omarchy/plugins"
  mv -- "$plugin_dir" "$backup_dir/removed/config/omarchy/plugins/neon-overdrive.cava"
  omarchy-shell shell rescanPlugins >/dev/null
fi

if [[ -f $autostart_file ]]; then
  begin_count=$(grep -Fxc -- "$begin_marker" "$autostart_file" || true)
  end_count=$(grep -Fxc -- "$end_marker" "$autostart_file" || true)
  if [[ $begin_count == "$end_count" && $begin_count -le 1 ]]; then
    if ((begin_count == 1)); then
      if awk -v begin="$begin_marker" -v end="$end_marker" '
        $0 == begin { begin_line = NR }
        $0 == end { end_line = NR }
        END { exit !(begin_line > 0 && end_line > begin_line) }
      ' "$autostart_file"; then
        autostart_tmp=$(mktemp "$autostart_file.tmp.XXXXXX")
        awk -v begin="$begin_marker" -v end="$end_marker" '
          $0 == begin { managed = 1; next }
          $0 == end { managed = 0; next }
          !managed { lines[++count] = $0 }
          END {
            while (count > 0 && lines[count] == "") count--
            for (i = 1; i <= count; i++) print lines[i]
          }
        ' "$autostart_file" >"$autostart_tmp"
        if luac -p "$autostart_tmp"; then
          chmod --reference="$autostart_file" "$autostart_tmp"
          mv -- "$autostart_tmp" "$autostart_file"
        else
          rm -f -- "$autostart_tmp"
          warn "updated autostart configuration would be invalid; leaving $autostart_file unchanged"
        fi
      else
        warn "managed markers in $autostart_file are out of order; leaving the file unchanged"
      fi
    fi
  else
    warn "managed markers in $autostart_file are malformed; leaving the file unchanged"
  fi
fi

if [[ -e $wallpaper_bin ]] && grep -Fq 'Managed by Neon Overdrive' "$wallpaper_bin"; then
  install -d -m 700 -- "$backup_dir/removed/local/bin"
  mv -- "$wallpaper_bin" "$backup_dir/removed/local/bin/neon-overdrive-wallpaper"
fi
stash_managed local/share/neon-overdrive "$wallpaper_dir" "$wallpaper_dir/.neon-overdrive-managed"

current_theme=""
[[ -r $state_home/omarchy/current/theme.name ]] && read -r current_theme <"$state_home/omarchy/current/theme.name"
if [[ $current_theme == "$theme_name" && -n $PREVIOUS_THEME && $PREVIOUS_THEME != "$theme_name" ]]; then
  if [[ -d $config_home/omarchy/themes/$PREVIOUS_THEME || -d /usr/share/omarchy/themes/$PREVIOUS_THEME ]]; then
    omarchy theme set "$PREVIOUS_THEME"
    current_theme="$PREVIOUS_THEME"
  else
    warn "previous theme '$PREVIOUS_THEME' is unavailable; keeping Neon Overdrive active"
  fi
fi

if [[ $THEME_WAS_COPIED == true && -f $theme_dir/.neon-overdrive-managed ]]; then
  if [[ $current_theme == "$theme_name" ]]; then
    warn "keeping the copied theme because it is still active"
  else
    install -d -m 700 -- "$backup_dir/removed/config/omarchy/themes"
    mv -- "$theme_dir" "$backup_dir/removed/config/omarchy/themes/neon-overdrive"
  fi
fi

if command -v hyprctl >/dev/null 2>&1 && hyprctl reload >/dev/null 2>&1; then
  config_errors=$(hyprctl configerrors)
  [[ -z $config_errors ]] || die "Hyprland rejected the updated config: $config_errors"
fi

if [[ -f $state_file ]]; then
  mv -- "$state_file" "$backup_dir/install-state.env"
fi

printf 'Neon Overdrive extras removed. Recovery backup: %s\n' "$backup_dir"
